# Generated by Django 5.0.4 on 2024-04-15 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicerequest',
            old_name='submitted_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='servicerequest',
            old_name='details',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='servicerequest',
            old_name='type',
            new_name='requester_name',
        ),
        migrations.RemoveField(
            model_name='servicerequest',
            name='attachment',
        ),
        migrations.RemoveField(
            model_name='servicerequest',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='servicerequest',
            name='resolved_at',
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='status',
            field=models.CharField(default='Pending', max_length=50),
        ),
    ]
