# Generated by Django 5.0.4 on 2024-04-15 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_rename_submitted_at_servicerequest_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='request_type',
            field=models.CharField(default='other', max_length=50),
        ),
    ]
